### ISSUE TITLE
64 bit compulsion

### ISSUE THREAD

**Issue by nitika18seraphic** [jhansireddy/AndroidScannerDemo#102]
Please update library as it is 32 bit and google play console requires 64 bit configuration.Library is good but having conflicts now.Please update its as soon as possible

**Comment by edwinjeppe1** [comment]
Have you found a way to upgrade this to 64bit ?

**Comment by nitika18seraphic** [comment]
I have tried to upgrade it by adding ndk.abi filters as it contains .so
files for 32 bit only.but it didn't work .try to make it fron 64 bit
machine and this problem is mainly because of native code which is used for
polygon crop

**Comment by edwinjeppe1** [comment]
I got it working by literally only taking the files from [here](https://github.com/jhansireddy/AndroidScannerDemo/tree/2cd23d3d362d0a6248cf489a79ebc4ba2c425c60/ScanDemoExample/scanlibrary/src/main/libs) and pasting it into the folder within my ScanLibrary location where they are located. It added the 64bit version libs for me.

**Comment by nitika18seraphic** [comment]
Yes same with me today . I successfully able to use this library again.

Thanks to you also

**Comment by jhansireddy** [comment]
Generated native libraries for all architectures now as part of https://github.com/jhansireddy/AndroidScannerDemo/commit/d29f33bb0aff512f9c90706f3fcf1804f368c75f
