### ISSUE TITLE
B&W filter issue

### ISSUE THREAD

**Issue by rishavsingla** [jhansireddy/AndroidScannerDemo#117]
I tried B&W filter. It does not work for me. Black Ink spread whereever the image is. So please help me

**Comment by vamsee9** [comment]
its OpenCV's defect you need to adjust threshold levels in code

**Comment by maxakash** [comment]
I have made changes to above values, but they are not visible in the app. I have even tried cleaning the project.

**Comment by jhansireddy** [comment]
You should do an NDK build after changing the scan.cpp

**Comment by maxakash** [comment]
I am new to ndk build.
Can you please tell me how to do it?

@jhansireddy

**Comment by jhansireddy** [comment]
https://developer.android.com/ndk/guides
