### ISSUE TITLE
Not Working in sdk version 29

### ISSUE THREAD

**Issue by KavinNallasamy** [jhansireddy/AndroidScannerDemo#120]
Library not working in sdk 28 and above. kindly, give update for latest version sdk

**Comment by vamsee9** [comment]
it's working perfectly SDK 21 to 30

**Comment by Reuben-cyber** [comment]
> it's working perfectly SDK 21 can you please tell how ..the app crashes when i open the scan button

**Comment by vamsee9** [comment]
Bro make new project and import this project as new module this content is out dated sis didn't update it

**Comment by Reuben-cyber** [comment]
> Bro make new project and import this project as new module this content is out dated sis didn't update it

i added as new module ...what do i do ahead ...im new to android ..so...

**Comment by vamsee9** [comment]
Ping me here [t.me/vamsee9](t.me/vamsee9)

**Comment by Reuben-cyber** [comment]
> Ping me here [t.me/vamsee9](t.me/vamsee9)

its showing me page not found

**Comment by vamsee9** [comment]
It's telegram app

**Comment by Reuben-cyber** [comment]
oh ..okay

**Comment by Reuben-cyber** [comment]
> Issues fixed

can u share the solution?

**Comment by fer314** [comment]
I fixed it by adding "<uses-feature android:name="android.hardware.camera"/>" to permissions on the android manifest

**Comment by jhansireddy** [comment]
Upgraded to compileSdkVersion of 30. Please reopen the issue if it is not fixed.
