### ISSUE TITLE
this is not working on android 10 or api above 29 please respond

### ISSUE THREAD

**Issue by babbar1989** [jhansireddy/AndroidScannerDemo#121]

**Comment by vamsee9** [comment]
Same here near to the solution need some time to find out

**Comment by Reuben-cyber** [comment]
anyone got any solution?

**Comment by vamsee9** [comment]
No i am on it soon will post if it works

**Comment by fer314** [comment]
I fixed it by adding <uses-feature android:name="android.hardware.camera"/ to the android manifest

**Comment by vamsee9** [comment]
> I fixed it by adding <uses-feature android:name="android.hardware.camera"/ to the android manifest

is it working ?

**Comment by jhansireddy** [comment]
Upgraded to compileSdkVersion 30 and it works fine.
