### ISSUE TITLE
Add new methods in scan.cpp

### ISSUE THREAD

**Issue by aashitshah26** [jhansireddy/AndroidScannerDemo#124]
Hey First of all thank you for this great library.I want to add new methods in scan.cpp . I have added the method but it is not reflecting the the so files . What should i do reflect those changes ? I am rather new in android programming using native code . Any assistance will be very helpful . Thank you.

**Comment by jhansireddy** [comment]
You should do an ndk build which would regenerate the .so files again.

**Comment by aashitshah26** [comment]
Thank you @jhansireddy  that did the trick .

**Comment by vamsee9** [comment]
> Hey First of all thank you for this great library.I want to add new methods in scan.cpp . I have added the method but it is not reflecting the the so files . What should i do reflect those changes ? I am rather new in android programming using native code . Any assistance will be very helpful . Thank you.

what are those changes can you please let me know
