### ISSUE TITLE
Change directory of images

### ISSUE THREAD

**Issue by HamzaArifS** [jhansireddy/AndroidScannerDemo#126]
Please tell me how to change the directory of the image. I want to make new directory in gallery and save pictures there

**Comment by vamsee9** [comment]
I think it's in scanlibrary -> res -> XML in this some thing file name like provider_.  .xml

**Comment by HamzaArifS** [comment]
i tried to change path but when i changed it app crashes

**Comment by vamsee9** [comment]
Yeah same here but you need to do some changes in scanconstants.java and some other files in scanlibrary Java files need to figure out which files save scanned image bitmaps for me it's saving in pictures

**Comment by HamzaArifS** [comment]
Will you plz specify the code

**Comment by vamsee9** [comment]
I too don't know I am checking out

**Comment by HamzaArifS** [comment]
okay sir. If u get it plz update me too

**Comment by vamsee9** [comment]
Sure you too work on it we will find them you can contact me at direct message at

**Comment by HamzaArifS** [comment]
done sir

**Comment by wazimBadsha** [comment]
@HamzaArifS  @vamsee9  guys, did you got solution?

**Comment by vamsee9** [comment]
No actual I am on it but didn't find any solution

**Comment by HamzaArifS** [comment]
No, I couldn't find too

**Comment by vamsee9** [comment]
got solution public final static String IMAGE_PATH = getActivity().getExternalFilesDir(null).getAbsolutePath() + "/scannedimage"

**Comment by vamsee9** [comment]
Is this useful ?

**Comment by HamzaArifS** [comment]
Maybe someone would help

**Comment by vamsee9** [comment]
I changed some have files

**Comment by HamzaArifS** [comment]
did something useful happen?

**Comment by vamsee9** [comment]
Yes I am testing it and will ping tomorrow

**Comment by HamzaArifS** [comment]
That's a really good news. I will wait

**Comment by HamzaArifS** [comment]
did the solution work? @vamsee9
