### ISSUE TITLE
Saving New Image is Removing Previous Image

### ISSUE THREAD

**Issue by Priyanshu-CODERX** [jhansireddy/AndroidScannerDemo#127]
Okay so what actually is happening that after saving the first clicked image from my app if gets saved but whenever I am clicking the second image from my app its removing the first clicked image and getting the 2nd clicked image save. I don't know how to fix it and also it gets save in a folder named scanSample and also I can't view the image from it through image gallery.

**Comment by vamsee9** [comment]
send log here, please
