### ISSUE TITLE
Support for Android 10

### ISSUE THREAD

**Issue by DeepaliMundaye** [jhansireddy/AndroidScannerDemo#134]
Hi Team,

You have done great job of polygonal cropping.
I have implemented this library in my projects since 2017.
Now our client want app which will support Android 10 as well.
In the latest library update build.gradle file, it is upto Android 9 only .
So can you please confirm that will this same library support Android 10 or will there be any update?

**Comment by fer314** [comment]
It works, but only by adding  <uses-feature android:name="android.hardware.camera"/ to android manifest for newest versions of android

**Comment by jhansireddy** [comment]
Library is upgraded to Android X with latest PR merge.
