### ISSUE TITLE
OpenCV Issue with large Image file of 2-5MB File

### ISSUE THREAD

**Issue by m-ajitabh** [jhansireddy/AndroidScannerDemo#15]
While Uploading High Resolution Image, OpenCv throws

1. Out of memory Exception , and

2. cv::error(): OpenCV Error: Assertion failed (8) in H, file , line 175 03-15 22:32:18.532

**Comment by nilasissen** [comment]
any solution for this issue ??

**Comment by DroidNinja** [comment]
When you input 2-5MB file, it takes a lot of time to detect contours edges of bitmap even in background thread. You must scale a bitmap to certain width and height and input the scaled bitmap.

**Comment by RozinaDarediya** [comment]
@DroidNinja  
I am having the following error 
`OpenCV Error: Assertion failed (scn == 3 || scn == 4) in void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)`

while changing in **scan.cpp** file as below
`cvtColor(mbgra, dst, CV_BGR2GRAY);`
i want to change it to **CV_GRAY2BGR565** it gives error as below

It would be very helpful to me if you can answer me.
Thank you
