### ISSUE TITLE
Scanning from Camera doesn't work for API Level 30

### ISSUE THREAD

**Issue by rahim4one** [jhansireddy/AndroidScannerDemo#150]
This library works perfect with picking image from gallery, but the CAMERA support doesn't works on API Level 30.

**Comment by kpradeepkumarreddy** [comment]
I'm planning to use this library. What is the error you are getting ?
and i tried the apk provided in this repo, After i take picture from camera, the image is getting rotated. Are you facing this issue ?
[https://github.com/jhansireddy/AndroidScannerDemo/tree/master/ScanDemoExample/apk/app-debug.apk](url)

**Comment by rahim4one** [comment]
> I'm planning to use this library. What is the error you are getting ?
> and i tried the apk provided in this repo, After i take picture from camera, the image is getting rotated. Are you facing this issue ?
> [https://github.com/jhansireddy/AndroidScannerDemo/tree/master/ScanDemoExample/apk/app-debug.apk](url)

No bro, i didn't faced anything like this.

**Comment by rahim4one** [comment]
**SOLVED**: we just need to ask for INTERNAL READ, WRITE and Camera Permissions to enabled very initially, in case we miss it, the library becomes unusable.

Thank You,
