### ISSUE TITLE
OpenCV import

### ISSUE THREAD

**Issue by StulleBrot** [jhansireddy/AndroidScannerDemo#2]
Hey,
i wanted to test your sample project.
Did the same sample project as you with your scanLibrary in it.
The problem ist wenn ich compile it, i am becoming the error "Failure [INSTALL_FAILED_NO_MATCHING_ABIS]".
It is probably because i need to import openCV. But i dont know what you mean with that and what i must do.
Until i search hours, i thought i would just ask you.
Because i didnt found anything of opencv in your github.
Thanks in advance.

**Comment by StulleBrot** [comment]
Nvm. Im just to dumb^^ Did it again and it worked. Was just the emulator.
Ok. Another dumb question.
I searched your scannlibrary a bit and i didnt found a import of opencv.
Where did you use the framework ? Because i just want the crop thing. 
Thanks in advance
StulleBrot

**Comment by jhansireddy** [comment]
Hello,
I have integrated openCV (c++ framework) by writting NDK wrapper on top of it, check https://github.com/jhansireddy/AndroidScannerDemo/blob/master/ScanDemoExample/scanlibrary/src/main/jni/scan.cpp 

Thanks,
Jhansi

**Comment by StulleBrot** [comment]
Ah I see
Good that answers my question.
Thanks again.
