### ISSUE TITLE
Not working for devices with a 64bit processor

### ISSUE THREAD

**Issue by HappyDr0id** [jhansireddy/AndroidScannerDemo#20]
Hello,

The actual implementation of the ScanLibrary doesn't work for devices with a 64 bit processor, simply because OpenCV 2.4.11 doesn't support 64 bit platforms.
@neoscreenager has made a fork and a pull request with the OpenCV 3.1 version, which supports all platforms. You should try to integrate his modifications.

However, there is a problem with his fork : the OpenCV library load management. It seems that we have to use the OpenCVLoader class to load the library now, otherwise it will crash saying it didn't find the library. I described the solution to this problem in his pull request.

Thanks for your work ;)

**Comment by jhansireddy** [comment]
Upgraded OpenCV to 3.1 version and supporting all platforms, let me know if it supports 64 bit platforms.
