### ISSUE TITLE
Security vulnerability.

### ISSUE THREAD

**Issue by paullouis-in** [jhansireddy/AndroidScannerDemo#22]
Your app is using a version of **libpng** containing a **security vulnerability.** Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.

The way to fix google provided:
https://support.google.com/faqs/answer/7011127

**Comment by wolmirgarbin** [comment]
Hello, I have the same problem, managed to find a solution or someone could indicate what to do?

**Comment by sunil-singh-chaudhary** [comment]
updated the sdk to latest Version opencv 3.0.1 in your scanlibraray ,may it omit your google security dialog

**Comment by m-ajitabh** [comment]
Getting a security warning message on the google play store of Libpng Vulnerability.

https://support.google.com/faqs/answer/7011127

**Comment by sunil-singh-chaudhary** [comment]
Update your opencv sdk it will solve

**Comment by m-ajitabh** [comment]
Thanks for the quick reply.
I have updated the SDK to OpenCV 3.1.0, After uploading the App into PlayStore, I will give my feedback.

**Comment by tuxtux59** [comment]
We just need to copy/replace etc java and native folders from newest opencv library in sdk folder?
Anyone knows if Google can say if security breach is covered from an APK posted in beta or alpha channel?
@m-ajitabh what's your feedback from your opencv changment?

Thanks

**Comment by m-ajitabh** [comment]
Yes, by copying new sdk to the project has removed my security breach
problem

**Comment by tuxtux59** [comment]
I still have the libpng security vunerability warning from google after opencv update, any solution to solve this?

**Comment by m-ajitabh** [comment]
Update with opencv 3.1 sdk

**Comment by tuxtux59** [comment]
@m-ajitabh : 3.1.0 is the one I downloaded and installed :/

**Comment by tuxtux59** [comment]
Is there really only these 3 folders to update and nothing else? cause if it's this it's not working on my app . Is anyone has another idea?

**Comment by DroidNinja** [comment]
Updating to opencv 3.1 removes the libpng warning. I have included latest sdk. Check out this repo: https://github.com/DroidNinja/Document-Scanner

**Comment by tuxtux59** [comment]
Its like the fifth try I made on my app replacing the three folders in SDK folder and Play store keep saying me that still a problem with libpng

**Comment by tuxtux59** [comment]
Need I to make a compilation or something cause I checked @DroidNinja repo and replace files that you changed , Google told me that this new APK is secure but all feature that i use on my app not work (Edge detection & creation of cropped image). Those feature present in scan.cpp (jni folder )?

**Comment by DroidNinja** [comment]
@tuxtux59 So you mean scan.cpp is not compiling? And you cant able to access any methods?

**Comment by tuxtux59** [comment]
@DroidNinja I don't know what you really mean by "not compiling" but I've two method in my scan.cpp that works on my unsecure APK version called natively from java code and when I call them the system tells me that those methods are unresolvable.
Few weeks ago I've a user that could not access to these method two but result of some memory management of Samsung that move appart the library core, so I used extern "c" encapsulation around those methods and it worked, but now i guess I will try to remove those encapsulations but I think that is not the real problem.
Have you some ideas? Need I some compilation of the core code of jni files?

**Comment by ketencek** [comment]
Hello

I have updated Opencv version to 3.1.0 in JNI folder. 

But i think error with libopencv_java.so file. Google can't accept this and gave me alert.

Can anybody help me to sortout this ?

Thank you

**Comment by alefcarlos** [comment]
@ketencek, You should see @DroidNinja 's repo! He has fixed it. I have cloned his repo and then I installed Android NDK, because he always compiles the lib on build. 
It solved my troubles with openCV lib!!

**Comment by m-ajitabh** [comment]
Hi Alef Carlos,

would you please send us the libraries, I am still getting the libpng issue.


Thanks
Ajitabh Ranjan
Mob: 9430331985

**Comment by alefcarlos** [comment]
Hi, m-ajitabh !

I have followed these steps:

- Clone the @DroidNinja 's repo;
- Compare differences between DroidNinja and this repo
- I found differences on Gradle, in scanlibrary/build.gradle, he added a task to compile scanlibrary every build.
- I downloaded NDK, and I configured its path in Android Studio.
- The openCv lib wasn't loading, because he changed some namespaces into .h file and he was using opencv_java3, to load the lib(app/src/main/java/vi/pdfscanner/main/ScannerEngine, scanlibrary/src/main/jni/vi_pdfscanner_main_ScannerEngine)
- I'm newbie on Android, i'm still learning, but I changed the .h file and also scan.cpp(I don't know if it is right, but It worked) – I  didn’t know how to generate .h file
- All the lines with vi_pdfscanner_main_ScannerEngine, I changed to default: com_scanlibrary_ScanActivity( ScanDemoExample/scanlibrary/src/main/jni/com_scanlibrary_ScanActivity) and changed the line that loads the openCV lib to opencv_java3

I hope that it helps you !

**Comment by jhansireddy** [comment]
Upgraded to openCv 3.1.
