### ISSUE TITLE
Set zoom in pointers

### ISSUE THREAD

**Issue by Testinha420** [jhansireddy/AndroidScannerDemo#24]
Can i put a zoom when user hold your finger on the points?

Like CamScanner:
![13707601_500666363461461_4568449541935154153_n](https://cloud.githubusercontent.com/assets/8333067/16853113/6fa4bc4e-49e1-11e6-9f0d-0c15e3e6e838.jpg)

**Comment by jhansireddy** [comment]
As of now this feature of zooming when user hold your finger on the points is not implemented in this Scanner.
