### ISSUE TITLE
libpng vulnerability issue when publishing app using this library. How to upgrade the libpng in this library.

### ISSUE THREAD

**Issue by anuraj381** [jhansireddy/AndroidScannerDemo#26]

**Comment by jhansireddy** [comment]
Upgraded OpenCV to 3.1 version which should possibly resolve the libpng issues.

Let me know if that helps

**Comment by SumanPahari** [comment]
Thank you very much.It s working fine .

**Comment by tuxtux59** [comment]
Thanks a lot !

**Comment by hanishsharma** [comment]
Hello all,

I have updated the OpenCV to 3.1 version and uploaded the latest apk on play store. But still my application is not getting uploaded and getting the same error, mentioned in the question.

Please help!

**Comment by SumanPahari** [comment]
I face the same problem on previous version of OpenCV .But after update 3.1 version ,solved the issue.
