### ISSUE TITLE
Would be great to have this project ported to a Cordova plugin for both platforms (Android and iOS)

### ISSUE THREAD

**Issue by saormart** [jhansireddy/AndroidScannerDemo#31]

**Comment by jhansireddy** [comment]
Agreed, but currently its built on native android. We will have to completely rebuilt it if we have to port it to cordova plugin.

**Comment by saormart** [comment]
Hi jhansireddy, thanks for your answer ! I know that's a really complicated task to do!
I don't have skills to create a plugin (not yet), but I'm sure that out of there there's people with skills and also people looking for this kind of solution !
This project is awesome ! And this is why I was thinking to have this project ported to Cordova for both (Android / iOS) !
By the way, I found some interesting link [here](http://www.pyimagesearch.com/2014/09/01/build-kick-ass-mobile-document-scanner-just-5-minutes/) that the guy build some think like this but in Pyton using OpenCV library (maybe it's just an idea to some one with skills to port to Cordova) !
I really appreciate your reply ! Let's see may some one do it ! :)

**Comment by jhansireddy** [comment]
Thanks :)
