### ISSUE TITLE
Improve APK size

### ISSUE THREAD

**Issue by khrizt** [jhansireddy/AndroidScannerDemo#33]
Hi,

I came across this project and I wanted to include it in my app, but I was wondering if there's a way to improve the APK size. Creating a simple app with a button and the scanlibrary creates a 22.5MB apk. Is there a way to improve that?

Thanks

**Comment by alex-amenos** [comment]
@khrizt You can generate multiple apks for different architectures to reduce the size of the app.

Build Multiple APKs:
https://developer.android.com/studio/build/configure-apk-splits.html

**Comment by khrizt** [comment]
That's true. Thanks a lot.
