### ISSUE TITLE
Failed to allocate a 51916812 byte allocation with 16777216 free bytes and 21MB until OOM

### ISSUE THREAD

**Issue by MinchinWang** [jhansireddy/AndroidScannerDemo#39]
Failed to allocate a 51916812 byte allocation with 16777216 free bytes and 21MB until OOM

  static public Bitmap createMyBitmap(int[] colors, int width, int height){
        Bitmap bmp = null;
        try {
            bmp = Bitmap.createBitmap(colors, 0, width, width, height,
                    Bitmap.Config.ARGB_8888);
        } catch (Exception e) {
            return null;
        }
        return bmp;

    }
why？

**Comment by jhansireddy** [comment]
Since, it doesn't have sufficient memory to allocate the app it crashed with out of memory issue.
