### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by karanmamtora** [jhansireddy/AndroidScannerDemo#43]
Installation failed with message Failed to finalize session : INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.karanm.scandemo-1: Can't install because provider name com.scanlibrary.provider (in package com.karanm.scandemo) is already used by com.scanner.demo.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

**Comment by jhansireddy** [comment]
Looks like you have first installed the application and then changed the package name and tried to install it again. Please try by uninstalling the first installed app and then install the one with new package name.
