### ISSUE TITLE
Libpng error while make release on Google Play

### ISSUE THREAD

**Issue by Cuesoft1** [jhansireddy/AndroidScannerDemo#44]
# Libpng Error

I made one App like scanner in this i use this library, It works fine but when i make signed and upload it on Google Play it gives Libpng  error.

I already updates Libpng library version 1.6.xx. I also updated OpenCv dependancy version 3.1. Still I Got this Error. plz solve this and update library
![libpng_error](https://user-images.githubusercontent.com/17155584/26964118-c1a562d4-4d0d-11e7-880b-7d48c68bea27.png)

**Comment by jordangraft** [comment]
I think its due to the OpenCV library being < 2.4

**Comment by jhansireddy** [comment]
This issue was resolved once we upgraded to OpenCV 3.1. I am not sure why you are seeing it now.
