### ISSUE TITLE
couldn't find "libopencv_java3.so

### ISSUE THREAD

**Issue by shweta16oct** [jhansireddy/AndroidScannerDemo#46]
Hello Team,
 I am facing with this issue when i run my app in android phone with  cpu 64.Please provide the solution.

"  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader [DexPathList[[zip file "/data/..../base.apk"],nativeLibraryDirectories=[/data/......./lib/arm64, /data/..../base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libopencv_java3.so"  "

**Comment by swarna-arjun** [comment]
I've got the same error on Samsung A5, while it works on Samsung Edge S7 and Samsung Note 4. Any particular reason why we get this error on some devices?

**Comment by swarna-arjun** [comment]
Found a solution that I picked from here:
[https://github.com/yixia/VitamioBundle/issues/305]

If you are using Android studio, just edit the gradle.properties in the root folder and add android.useDeprecatedNdk=true. Then edit the build.gradle file in your app's folder, set abiFilters as below:

android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }
}

**Comment by shweta16oct** [comment]
Thank you , 
Now it is working fine.

**Comment by HardikMaru** [comment]
Thanks @swarna-arjun. Your solution is working for me as well.

Further more I removed line "android.useDeprecatedNdk=true" from gradle.properties and it is still working fine.

However I think library shall provide support for 64 bit devices by providing its library files for "arm64-v8a", "mips64" and "x86_64".

Thanks @jhansireddy as well for saving our days. :)

**Comment by ShlomieRottenberg** [comment]
There is a branch by vinny1575 that provides 64-bit libraries [here](https://github.com/jhansireddy/AndroidScannerDemo/blob/2cd23d3d362d0a6248cf489a79ebc4ba2c425c60/ScanDemoExample/scanlibrary/src/main/libs)
