### ISSUE TITLE
Permission denial Camera intent isn't working, i have tried my best but till now its not working

### ISSUE THREAD

**Issue by vixcypandit** [jhansireddy/AndroidScannerDemo#47]

**Comment by vikasWri** [comment]
Are you provide run time permission to the App. If not so please do
 Here is the reference [https://stackoverflow.com/questions/44650229/run-time-user-permission-dialog-not-showing-in-noughat/44650453#44650453](Runtime Permission)

**Comment by thakurmayu07** [comment]
Go to library's manifest.xml and comment camera permission. I don't know why this library need camera permission if it is using intent to capture camera

**Comment by MincDev** [comment]
@thakurmayu07 @vixcypandit @vikasWri DO NOT REMOVE PERMISSION FROM THE SCANNER MANIFEST. Simply add a check in the ScanActivity for permission and then request permission if needed.
