### ISSUE TITLE
libScanner.so native library not on x86 architecture

### ISSUE THREAD

**Issue by HappyDr0id** [jhansireddy/AndroidScannerDemo#5]
Hello,

The native library libScanner.so is only available for the ARM architecture, is it possible to compile it for the x86 architecture too please ?
Otherwise, the module makes the application crashes this way on some x86 android emulators : 

java.lang.ExceptionInInitializerError
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load Scanner: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:365)
at java.lang.System.loadLibrary(System.java:535)

I don't it is also crashes on real x86 hardware devices, but I suspect it.
It will be great to be compatible with x86 devices too ;)

Thanks in advance

**Comment by HappyDr0id** [comment]
It is okay, finally I managed to execute a ndk-build command to generate native librairies for the x86 architecture. I will certainly submit you a pull request with new files for x86.

**Comment by dheerajkatarya** [comment]
Could you please share x86 libScanner.so

**Comment by HappyDr0id** [comment]
I just made a pull request to integrate the libraries for x86

**Comment by dheerajkatarya** [comment]
Thanks a lot  Buddy.

**Comment by nareshlalchandani** [comment]
Hello Dear,

I am facing same issue.

When i run for 32 bit it's working fine on my mobile. but playstore not accepting release. And when i build for 64 its not working in mobile but playstore accepted it.


Can you please help me out to get .so file for both the Architecture(32 and 64)
