### ISSUE TITLE
How to save the edited image

### ISSUE THREAD

**Issue by ReibenD** [jhansireddy/AndroidScannerDemo#56]
I'm using your repository

I have tried to save the edited image but I have not succeeded.

Within which file is the action configured?

Because only the original image is saved in the directory and with the name defined but I have not found the settings to save the edited image

**Comment by jhansireddy** [comment]
Hi ReibenD, 

The Scanned image would not be saved in the directory. This library would return the scanned image to the initial Activity which started the scanning. 

Refer to https://github.com/jhansireddy/AndroidScannerDemo/blob/master/ScanDemoExample/app/src/main/java/com/scanner/demo/MainActivity.java onActivityResult method.
