### ISSUE TITLE
App Not installed

### ISSUE THREAD

**Issue by rizauddin446** [jhansireddy/AndroidScannerDemo#59]
Hello,
We have used this library in two apps. one app Already installed in mobile and when I try to install second app  getting an error saying "APP NOT INSTALLED". Any Solution please let me know. Very Urgent.

**Comment by LamraniOthmane** [comment]
They use the same package name i think

**Comment by gSrikar** [comment]
They both have the same provider authority("com.scanlibrary.provider"). Keep it different and you will be able to install multiple apps with the library in them.
