### ISSUE TITLE
Automatic edge detection

### ISSUE THREAD

**Issue by abdurrahimbliss** [jhansireddy/AndroidScannerDemo#7]
Any plans for automatic edge detection? Or how to do it using opencv? Can you give some directions? Thanks.

**Comment by jhansireddy** [comment]
Got in automatic edge detection into this but, its not very matured.

Edge detection can be done by first determining the lines and then intersection points of the lines and then joining the points.

Please refer to getPoints method, line 23 in https://github.com/jhansireddy/AndroidScannerDemo/blob/master/ScanDemoExample/scanlibrary/src/main/jni/scan.cpp
