### ISSUE TITLE
Gradle Issue

### ISSUE THREAD

**Issue by softwrengr** [jhansireddy/AndroidScannerDemo#74]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :scanlibrary.

how to solve this issue ?  I am stuck. your kind help will be appreciated.

**Comment by scorchknight** [comment]
Do you have this in your build.gradle :


dependencies {
    compile project(':scanlibrary')

**Comment by ayushpant1** [comment]
My gradle is not building after adding compile project(':scanlibrary').It's showing following issue
Project with path ':scanlibrary' could not be found in project ':app'.
Thank u in advance for the help..

**Comment by MincDev** [comment]
@ayushpant1 you have to include the scanlibrary in your project. Go to your settings.gradle file and you will see the line `include ':app'`. Add a second line saying `include ':scanlibrary'` or simply do one liner `include ':app', ':scanlibrary'`

Hope this helps.

**Comment by ayushpant1** [comment]
@MincDev Thanks buddy, It helped me.

**Comment by MincDev** [comment]
@ayushpant1 were you able to resolve the following issue:

> Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :scanlibrary.

**Comment by ayushpant1** [comment]
@MincDev I think this issue also occur due to not adding the scanlibrary through import Module option in Android Studio because in my case it was not added as a module an i was only adding the  ':scanlibrary'
in my gradle.

**Comment by MincDev** [comment]
@ayushpant1 Copy the scanlibrary folder to your project root and everything should compile. My mistake was I copied the folder inside my ‘app’ folder by mistake.

**Comment by ayushpant1** [comment]
@MincDev yeah and also we can import the module in Android studio and then include the library in Gradle.

**Comment by MincDev** [comment]
@ayushpant1 Could you have a look at issue [#80](https://github.com/jhansireddy/AndroidScannerDemo/issues/80)? Are you having the same issue?

**Comment by nileshdhola** [comment]
1. copy project in your root folder .
2. open settings.gradle import file name like - as per given module/project  name  : *include ':app', ':scanlibrary'*
3. file -> project structure ->app _ add dependencies  , add module  (click plus button + ) add module .
4. check build.grandle  -automatically add   compile project(':scanlibrary').
5. access lib for your code.

**Comment by adad184** [comment]
hi there,

> 1. copy project in your root folder .
> 2. open settings.gradle import file name like - as per given module/project  name  : _include ':app', ':scanlibrary'_
> 3. file -> project structure ->app _ add dependencies  , add module  (click plus button + ) add module .
> 4. check build.grandle  -automatically add   compile project(':scanlibrary').
> 5. access lib for your code.

@nileshdhola hi,

when i follow the step, 

```
    dependencies {
        implementation project(':scanlibrary')
        classpath 'com.android.tools.build:gradle:3.6.3'
    }
```
(I'm using gradle 3.6.3)
and i got 

```
Build file '/Users/xxx/Workspace/project/xxx/android/build.gradle' line: 8
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [project ':scanlibrary'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

So what should i do next?
