### ISSUE TITLE
Scan Activity Not Opening

### ISSUE THREAD

**Issue by theLastRaider** [jhansireddy/AndroidScannerDemo#76]
I want to start your scan homepage when my "SCAN" button is clicked but button is not working when no preference is passed using putExtra

**Comment by Deepak111992** [comment]
upload = (Button) findViewById(R.id.btn_logo);
        upload.setOnClickListener(new ScanButtonClickListener(ScanConstants.OPEN_MEDIA));

**Comment by theLastRaider** [comment]
This will open media but I want the home page

**Comment by Deepak111992** [comment]
To open homepage  i.e scanning page,first you have to upload something for scanning .

**Comment by theLastRaider** [comment]
Can you share the code snippet or how to open the home page?

**Comment by Deepak111992** [comment]
Download the project,you will get everything there .

**Comment by thecqf** [comment]
same i couldnt open the homepage when passing 0 as preference, and i couldnt find anything in the project

**Comment by jhansireddy** [comment]
When you say Scan Home, do you mean the Image to crop with selection polygon? May be you could have directly started ScanActivity.
