### ISSUE TITLE
libScanner.so for arm64

### ISSUE THREAD

**Issue by jsonmat** [jhansireddy/AndroidScannerDemo#77]
Hello there! I really love your work, especially this one! However, how do I get the libScanner.so for arm64 (for 64-bit)?

Thanks!

**Comment by jsonmat** [comment]
Is anyone here??? I really need help! Please :(

**Comment by tuanlamsts** [comment]
Hey anyone have libScanner.so for arm64?

**Comment by jhansireddy** [comment]
Generated native libraries for all architectures as part of https://github.com/jhansireddy/AndroidScannerDemo/commit/d29f33bb0aff512f9c90706f3fcf1804f368c75f
