### ISSUE TITLE
i face problem to run this project

### ISSUE THREAD

**Issue by waqasawan44** [jhansireddy/AndroidScannerDemo#8]
Plz tell me how i used it step by step tell me i used but app is unfortunately stop
![capture](https://cloud.githubusercontent.com/assets/15631866/12073884/0da22936-b0ea-11e5-98cb-50c00d443627.PNG)
it is possible you tell me all step how it import in eclipse and how Opencv library used and How scan library used i has no any idea about it please tell me
actually my final project is same as its last week to submit it .....................

**Comment by jhansireddy** [comment]
It is not able to find the ScanActivity, please check if you have imported the project correctly without missing the ScanLibrary.

**Comment by waqasawan44** [comment]
i import it but also not find it
