### ISSUE TITLE
Polygons Not Showing

### ISSUE THREAD

**Issue by MincDev** [jhansireddy/AndroidScannerDemo#80]
Hi

When running the Demo app everything works but when including the app into my project the polygons disappear and I am unable to crop the image. Has anyone else experienced this?

**Comment by ayushpant1** [comment]
@MincDev I guess instead of copying the scanlibrary module to your project you can simply import the module in Android Studio and the add this line to your gradle
` compile project(':scanlibrary')`

I don't know the exact answer but you can try this one.

Hope this will help.

**Comment by MincDev** [comment]
@ayushpant1 thanks for the reply. I did import the module but it still does not display the polygons. It detects the documents but does not allow the user to crop using the polygons as they do not display at all. :(

**Comment by MincDev** [comment]
No problem mate.. still trying to figure out why it wont work but will get it eventually :)

**Comment by MincDev** [comment]
@ayushpant1 have you also imported the openCVLibrary as a module?

**Comment by ayushpant1** [comment]
@MincDev Yeah, Following Link was helpful for me:
[https://blog.codeonion.com/2015/11/25/creating-a-new-opencv-project-in-android-studio/](url)

**Comment by MincDev** [comment]
@ayushpant1 I created a new android project with a single button and imported the scanlibrary.. everything works as expected (without importing new opencv) however in my actual app it does not.. this is very strange

**Comment by ayushpant1** [comment]
@MincDev Try importing openCV in that project and then see it works or not.

**Comment by MincDev** [comment]
@ayushpant1 I have imported it as well. I have event tried using the forked version of the scanlibrary where you do not need to import the module at all. Something in my app is preventing those polygons from displaying and finding the issue is a huge pain..

**Comment by ayushpant1** [comment]
Can you share your code with me? This way it will be more helpful.

**Comment by MincDev** [comment]
@ayushpant1 do you need the entire project or what parts of the code? The app is currently live. If you need the entire project I might need to request permission for you to get access to the project. I can send you code snippets though without permission.

**Comment by ayushpant1** [comment]
@MincDev If i will get access to the whole project that will be more help for me.Can u share it?

**Comment by MincDev** [comment]
@ayushpant1 I will request permission from my employer and get back to you.

**Comment by ayushpant1** [comment]
@MincDev ok No problem!!!

**Comment by DevAhamed** [comment]
@MincDev Check whether you are using a drawable named 'circle'

**Comment by DevAhamed** [comment]
@MincDev Glad this is resolved
