### ISSUE TITLE
What is the location of the saved image?

### ISSUE THREAD

**Issue by pankurocks** [jhansireddy/AndroidScannerDemo#83]
I can't find the saved image after scanning it. Where the image is saving in the phone. I checked and find the path but my photos are not saving. What is the problem?

**Comment by MathewsNyirongo** [comment]
I'm facing the same problem...where are the scanned images saved?

**Comment by akshaybenk** [comment]
`getContentResolver().delete(uri, null, null);`
the above line is present in onActivitResult method.
You can comment it, to see the scanned image stored in pictures directory in the internal storage of the device
