### ISSUE TITLE
I can not get back to the fragment of the main activity that called scanlibrary

### ISSUE THREAD

**Issue by massimilianochiodi** [jhansireddy/AndroidScannerDemo#93]
Hey! Ciao da Italy 

I have a problem with your library, in practice I have an activity with lots of fragments.
launch the scanner activity from a fragment.
Everything works until the last moment when I press the 'save' button and my application goes into the background and restarts.

**Comment by jhansireddy** [comment]
If you think starting an Activity from a fragment is causing the problem, you should try to launch the  ScanFragment directly from your fragment or activity which implements from IScanner.

**Comment by massimilianochiodi** [comment]
Are only a stupid missing parameter in Manifest.
