### ISSUE TITLE
how to build libScanner.so library for openCV 4.0.1 

### ISSUE THREAD

**Issue by pankaj046** [jhansireddy/AndroidScannerDemo#96]

**Comment by CBerthias** [comment]
Did you find an answer ?

**Comment by sid4fun** [comment]
Did anyone find the answer?? i have old libScanner.so file for 32bit but i need 64bit version of the same.

**Comment by sid4fun** [comment]
> Did you find an answer ?

here you go
https://github.com/jhansireddy/AndroidScannerDemo/tree/2cd23d3d362d0a6248cf489a79ebc4ba2c425c60/ScanDemoExample/scanlibrary/src/main/libs

**Comment by pankaj046** [comment]
Not working for opencv 4.0.1

**Comment by sid4fun** [comment]
> Not working for opencv 4.0.1

how to check openCV version?

**Comment by jhansireddy** [comment]
Do you want to upgrade open cv or want to generate for 64 bit architectures? 
If it is about 64 bit architecture native libraries, they are now generated as part of https://github.com/jhansireddy/AndroidScannerDemo/commit/d29f33bb0aff512f9c90706f3fcf1804f368c75f
