### ISSUE TITLE
Scan library conflict  provider name issue 

### ISSUE THREAD

**Issue by Shubham-Kathe** [jhansireddy/AndroidScannerDemo#97]
![issue_scan_lib](https://user-images.githubusercontent.com/47270167/55703824-4c659d00-59f8-11e9-88de-a301f3efaccd.png)
I tried by changing its package name but then some jni lib getting issue 
Please help me to sort out this  issue

**Comment by pankaj046** [comment]
1) this is not library problem uninstall existing app install new build app 
2) restart android studio and your phone and install new build app

**Comment by Shubham-Kathe** [comment]
@pankaj046  There are two different application which used this same scan library.

**Comment by LokeshZade** [comment]
change authorities name of provider in manifest
